# Generated by Django 3.1 on 2021-04-21 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Есіміңіз')),
                ('last_name', models.CharField(blank=True, default='Білмеймін', max_length=40, verbose_name='Әкеңіз')),
                ('third_name', models.CharField(blank=True, default='Білмеймін', max_length=40, verbose_name='Атаңыз')),
                ('fourth_name', models.CharField(blank=True, default='Білмеймін', max_length=40, verbose_name='Атаңыздың әкесі')),
                ('fiveth_name', models.CharField(blank=True, default='Білмеймін', max_length=40, verbose_name='Атаңыздың атасы')),
                ('sixth_name', models.CharField(blank=True, default='Білмеймін', max_length=40, verbose_name='Атаңыздың атасының әкесі')),
                ('seventh_name', models.CharField(blank=True, default='Білмеймін', max_length=40, verbose_name='Оның атасы')),
                ('biog', models.TextField(verbose_name='Өзіңіз жайында')),
                ('birth_day', models.CharField(max_length=3, verbose_name='Туылған күні')),
                ('birth_mounth', models.CharField(max_length=20, verbose_name='Туылған Айы')),
                ('birth_year', models.CharField(max_length=4, verbose_name='Туылған Жылы')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Уақыты')),
                ('contact_number', models.CharField(max_length=11, verbose_name='Байланыс телефоны')),
                ('facebook', models.CharField(blank=True, max_length=250, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=250, verbose_name='Instagram')),
                ('whatsapp', models.CharField(blank=True, max_length=12, verbose_name='Whatsapp')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
