# Generated by Django 3.1 on 2021-04-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210422_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='jynys',
            field=models.CharField(default='Білмеймін', max_length=4, verbose_name='Жынысыныз'),
        ),
    ]
