# Generated by Django 3.1 on 2021-04-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_article_jynys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, verbose_name='Байланыс телефоны'),
        ),
        migrations.AlterField(
            model_name='article',
            name='instagram',
            field=models.CharField(max_length=250, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='article',
            name='jynys',
            field=models.CharField(max_length=4, verbose_name='Жынысыныз'),
        ),
    ]
