# Generated by Django 3.1 on 2021-04-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210424_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Уақыты'),
        ),
    ]
