# Generated by Django 3.1 on 2021-05-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210427_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, default='Пост', max_length=10, verbose_name='Категория'),
        ),
    ]
