# Generated by Django 3.1 on 2021-05-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, default='Іздеу', max_length=10, verbose_name='Категория'),
        ),
    ]
