# Generated by Django 3.1 on 2021-05-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210507_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='birth_year',
            field=models.CharField(max_length=150, verbose_name='Туылған Жылы'),
        ),
        migrations.AlterField(
            model_name='article',
            name='jynys',
            field=models.CharField(max_length=150, verbose_name='Жынысыныз'),
        ),
    ]
